### ISSUE TITLE
hz.ds is not a separate dataset

### ISSUE THREAD

**Issue by robertoostenveld** [Donders-Institute/meg-dataflow#2]
@hurngchunlee I see a script that does

````
#!/bin/bash
raw_dir=$1
min_back=$2
find $raw_dir -type f -path '*.ds/*' -mmin -${min_back} | awk -F '.ds' '{print $1".ds"}' | sort | uniq
````

that would also detect hz.ds and hz[0-9]*.ds as datasets. Those are not separate datasets but belong to the containing ds folder. They contain the short head-localization measurement at the start (and sometimes in between and/or at the end).

**Comment by robertoostenveld** [comment]
or does the "-mmin $min_back" prevent that somehow?

**Comment by hurngchunlee** [comment]
This is not relevant anymore.  Closing it.
